### ISSUE TITLE
option to expose program execution debug logs through the API

### ISSUE THREAD

**Issue by demmer** [juttle/juttle-service#42]
In order to help debug remotely executing programs, the juttle service jobs API should support an additional `debug` option along with the program bundle. When set, the system would include the logs generated by the given program alongside the program results (either streamed over the websocket or collected and included in the the REST API results when wait=true).

The implementation can piggy-back on the existing mechanism that handles logs generated from the subprocess by sending a message to the parent process. Currently this handler just delegates directly to log4js, but this new feature could tap in at the same point to be able to process the logs and send them to the client.

This approach would also provide the expected isolation -- only logs generated by a specific subprocess (i.e. a given juttle program) would be intercepted, so the logs from a given program run wouldn't be interleaved with the logs from another program run.

**Comment by VladVega** [comment]
Just a little sample of appender usage:
https://gist.github.com/VladVega/04da6c66e307b275b08b

**Comment by demmer** [comment]
I alluded this in the issue, but I don't think it will work to intercept at
the log4js level since all the logs for every executing juttle program use
the same log4js instance.

My thought was that we could intercept at the place where the job-manager
handles log messages coming from the child process:
https://github.com/juttle/juttle-service/blob/master/lib/juttle-job.js#L74

That way we only get the logs from the child process itself, which is one
to one with the job run request.


On Thu, Feb 11, 2016 at 5:24 PM, Vlad Vega <notifications@github.com> wrote:

> Just a little sample of appender usage:
> https://gist.github.com/VladVega/04da6c66e307b275b08b
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juttle/juttle-service/issues/42#issuecomment-183141788>
> .
>



-- 
Michael Demmer
Jut - CTO / VP Engineering
demmer@jut.io

**Comment by go-oleg** [comment]
A little late to this, but what about making the `debug` option something you set when connecting to a job via websocket instead of when creating a job? That way you could tap into the logs being generated by an already running job instead of having to recreate it with the `debug` option.
